/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdditionalAmount } from './AdditionalAmount';
import {
    AdditionalAmountFromJSON,
    AdditionalAmountFromJSONTyped,
    AdditionalAmountToJSON,
    AdditionalAmountToJSONTyped,
} from './AdditionalAmount';

/**
 * 
 * @export
 * @interface AddendumCreate
 */
export interface AddendumCreate {
    /**
     * 
     * @type {string}
     * @memberof AddendumCreate
     */
    addendumNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof AddendumCreate
     */
    addendumDate: Date;
    /**
     * 
     * @type {AdditionalAmount}
     * @memberof AddendumCreate
     */
    additionalAmount: AdditionalAmount;
    /**
     * 
     * @type {string}
     * @memberof AddendumCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the AddendumCreate interface.
 */
export function instanceOfAddendumCreate(value: object): value is AddendumCreate {
    if (!('addendumNumber' in value) || value['addendumNumber'] === undefined) return false;
    if (!('addendumDate' in value) || value['addendumDate'] === undefined) return false;
    if (!('additionalAmount' in value) || value['additionalAmount'] === undefined) return false;
    return true;
}

export function AddendumCreateFromJSON(json: any): AddendumCreate {
    return AddendumCreateFromJSONTyped(json, false);
}

export function AddendumCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddendumCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'addendumNumber': json['addendum_number'],
        'addendumDate': (new Date(json['addendum_date'])),
        'additionalAmount': AdditionalAmountFromJSON(json['additional_amount']),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AddendumCreateToJSON(json: any): AddendumCreate {
    return AddendumCreateToJSONTyped(json, false);
}

export function AddendumCreateToJSONTyped(value?: AddendumCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addendum_number': value['addendumNumber'],
        'addendum_date': ((value['addendumDate']).toISOString().substring(0,10)),
        'additional_amount': AdditionalAmountToJSON(value['additionalAmount']),
        'description': value['description'],
    };
}

