/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddendumResponse
 */
export interface AddendumResponse {
    /**
     * 
     * @type {string}
     * @memberof AddendumResponse
     */
    addendumNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof AddendumResponse
     */
    addendumDate: Date;
    /**
     * 
     * @type {string}
     * @memberof AddendumResponse
     */
    additionalAmount: string;
    /**
     * 
     * @type {string}
     * @memberof AddendumResponse
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddendumResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof AddendumResponse
     */
    contractId: number;
}

/**
 * Check if a given object implements the AddendumResponse interface.
 */
export function instanceOfAddendumResponse(value: object): value is AddendumResponse {
    if (!('addendumNumber' in value) || value['addendumNumber'] === undefined) return false;
    if (!('addendumDate' in value) || value['addendumDate'] === undefined) return false;
    if (!('additionalAmount' in value) || value['additionalAmount'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contractId' in value) || value['contractId'] === undefined) return false;
    return true;
}

export function AddendumResponseFromJSON(json: any): AddendumResponse {
    return AddendumResponseFromJSONTyped(json, false);
}

export function AddendumResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddendumResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'addendumNumber': json['addendum_number'],
        'addendumDate': (new Date(json['addendum_date'])),
        'additionalAmount': json['additional_amount'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'contractId': json['contract_id'],
    };
}

export function AddendumResponseToJSON(json: any): AddendumResponse {
    return AddendumResponseToJSONTyped(json, false);
}

export function AddendumResponseToJSONTyped(value?: AddendumResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addendum_number': value['addendumNumber'],
        'addendum_date': ((value['addendumDate']).toISOString().substring(0,10)),
        'additional_amount': value['additionalAmount'],
        'description': value['description'],
        'id': value['id'],
        'contract_id': value['contractId'],
    };
}

