/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdditionalAmount
 */
export interface AdditionalAmount {
}

/**
 * Check if a given object implements the AdditionalAmount interface.
 */
export function instanceOfAdditionalAmount(value: object): value is AdditionalAmount {
    return true;
}

export function AdditionalAmountFromJSON(json: any): AdditionalAmount {
    return AdditionalAmountFromJSONTyped(json, false);
}

export function AdditionalAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalAmount {
    return json;
}

export function AdditionalAmountToJSON(json: any): AdditionalAmount {
    return AdditionalAmountToJSONTyped(json, false);
}

export function AdditionalAmountToJSONTyped(value?: AdditionalAmount | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

