/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppendixCreate
 */
export interface AppendixCreate {
    /**
     * 
     * @type {string}
     * @memberof AppendixCreate
     */
    appendixNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof AppendixCreate
     */
    appendixDate: Date;
    /**
     * 
     * @type {string}
     * @memberof AppendixCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the AppendixCreate interface.
 */
export function instanceOfAppendixCreate(value: object): value is AppendixCreate {
    if (!('appendixNumber' in value) || value['appendixNumber'] === undefined) return false;
    if (!('appendixDate' in value) || value['appendixDate'] === undefined) return false;
    return true;
}

export function AppendixCreateFromJSON(json: any): AppendixCreate {
    return AppendixCreateFromJSONTyped(json, false);
}

export function AppendixCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppendixCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'appendixNumber': json['appendix_number'],
        'appendixDate': (new Date(json['appendix_date'])),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AppendixCreateToJSON(json: any): AppendixCreate {
    return AppendixCreateToJSONTyped(json, false);
}

export function AppendixCreateToJSONTyped(value?: AppendixCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appendix_number': value['appendixNumber'],
        'appendix_date': ((value['appendixDate']).toISOString().substring(0,10)),
        'description': value['description'],
    };
}

