/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppendixResponse
 */
export interface AppendixResponse {
    /**
     * 
     * @type {string}
     * @memberof AppendixResponse
     */
    appendixNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof AppendixResponse
     */
    appendixDate: Date;
    /**
     * 
     * @type {string}
     * @memberof AppendixResponse
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AppendixResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof AppendixResponse
     */
    contractId: number;
}

/**
 * Check if a given object implements the AppendixResponse interface.
 */
export function instanceOfAppendixResponse(value: object): value is AppendixResponse {
    if (!('appendixNumber' in value) || value['appendixNumber'] === undefined) return false;
    if (!('appendixDate' in value) || value['appendixDate'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contractId' in value) || value['contractId'] === undefined) return false;
    return true;
}

export function AppendixResponseFromJSON(json: any): AppendixResponse {
    return AppendixResponseFromJSONTyped(json, false);
}

export function AppendixResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppendixResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appendixNumber': json['appendix_number'],
        'appendixDate': (new Date(json['appendix_date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'contractId': json['contract_id'],
    };
}

export function AppendixResponseToJSON(json: any): AppendixResponse {
    return AppendixResponseToJSONTyped(json, false);
}

export function AppendixResponseToJSONTyped(value?: AppendixResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appendix_number': value['appendixNumber'],
        'appendix_date': ((value['appendixDate']).toISOString().substring(0,10)),
        'description': value['description'],
        'id': value['id'],
        'contract_id': value['contractId'],
    };
}

