/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeRate } from './ExchangeRate';
import {
    ExchangeRateFromJSON,
    ExchangeRateFromJSONTyped,
    ExchangeRateToJSON,
    ExchangeRateToJSONTyped,
} from './ExchangeRate';
import type { TotalPrice } from './TotalPrice';
import {
    TotalPriceFromJSON,
    TotalPriceFromJSONTyped,
    TotalPriceToJSON,
    TotalPriceToJSONTyped,
} from './TotalPrice';
import type { PricePerUnit } from './PricePerUnit';
import {
    PricePerUnitFromJSON,
    PricePerUnitFromJSONTyped,
    PricePerUnitToJSON,
    PricePerUnitToJSONTyped,
} from './PricePerUnit';

/**
 * Использует `ContractBase`, но отдельно определяет ID при создании.
 * @export
 * @interface ContractCreate
 */
export interface ContractCreate {
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    contractNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof ContractCreate
     */
    contractDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ContractCreate
     */
    validDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    placeOfSigning?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    currency?: string;
    /**
     * 
     * @type {ExchangeRate}
     * @memberof ContractCreate
     */
    exchangeRate?: ExchangeRate | null;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    supplierName: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    supplierRepresentative: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    supplierAddress: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    supplierBank: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    supplierAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    buyerName: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    buyerAddress: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    buyerBank: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    buyerAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    goodsName: string;
    /**
     * 
     * @type {number}
     * @memberof ContractCreate
     */
    quantity: number;
    /**
     * 
     * @type {PricePerUnit}
     * @memberof ContractCreate
     */
    pricePerUnit: PricePerUnit;
    /**
     * 
     * @type {TotalPrice}
     * @memberof ContractCreate
     */
    totalPrice: TotalPrice;
    /**
     * 
     * @type {Date}
     * @memberof ContractCreate
     */
    paymentDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ContractCreate
     */
    deliveryTerms: string;
    /**
     * 
     * @type {number}
     * @memberof ContractCreate
     */
    claimPeriod: number;
    /**
     * 
     * @type {number}
     * @memberof ContractCreate
     */
    responsePeriod: number;
}

/**
 * Check if a given object implements the ContractCreate interface.
 */
export function instanceOfContractCreate(value: object): value is ContractCreate {
    if (!('contractNumber' in value) || value['contractNumber'] === undefined) return false;
    if (!('contractDate' in value) || value['contractDate'] === undefined) return false;
    if (!('supplierName' in value) || value['supplierName'] === undefined) return false;
    if (!('supplierRepresentative' in value) || value['supplierRepresentative'] === undefined) return false;
    if (!('supplierAddress' in value) || value['supplierAddress'] === undefined) return false;
    if (!('supplierBank' in value) || value['supplierBank'] === undefined) return false;
    if (!('supplierAccount' in value) || value['supplierAccount'] === undefined) return false;
    if (!('buyerName' in value) || value['buyerName'] === undefined) return false;
    if (!('buyerAddress' in value) || value['buyerAddress'] === undefined) return false;
    if (!('buyerBank' in value) || value['buyerBank'] === undefined) return false;
    if (!('buyerAccount' in value) || value['buyerAccount'] === undefined) return false;
    if (!('goodsName' in value) || value['goodsName'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('pricePerUnit' in value) || value['pricePerUnit'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('paymentDate' in value) || value['paymentDate'] === undefined) return false;
    if (!('deliveryTerms' in value) || value['deliveryTerms'] === undefined) return false;
    if (!('claimPeriod' in value) || value['claimPeriod'] === undefined) return false;
    if (!('responsePeriod' in value) || value['responsePeriod'] === undefined) return false;
    return true;
}

export function ContractCreateFromJSON(json: any): ContractCreate {
    return ContractCreateFromJSONTyped(json, false);
}

export function ContractCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'contractNumber': json['contract_number'],
        'contractDate': (new Date(json['contract_date'])),
        'validDate': json['valid_date'] == null ? undefined : (new Date(json['valid_date'])),
        'placeOfSigning': json['place_of_signing'] == null ? undefined : json['place_of_signing'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'exchangeRate': json['exchange_rate'] == null ? undefined : ExchangeRateFromJSON(json['exchange_rate']),
        'supplierName': json['supplier_name'],
        'supplierRepresentative': json['supplier_representative'],
        'supplierAddress': json['supplier_address'],
        'supplierBank': json['supplier_bank'],
        'supplierAccount': json['supplier_account'],
        'buyerName': json['buyer_name'],
        'buyerAddress': json['buyer_address'],
        'buyerBank': json['buyer_bank'],
        'buyerAccount': json['buyer_account'],
        'goodsName': json['goods_name'],
        'quantity': json['quantity'],
        'pricePerUnit': PricePerUnitFromJSON(json['price_per_unit']),
        'totalPrice': TotalPriceFromJSON(json['total_price']),
        'paymentDate': (new Date(json['payment_date'])),
        'deliveryTerms': json['delivery_terms'],
        'claimPeriod': json['claim_period'],
        'responsePeriod': json['response_period'],
    };
}

export function ContractCreateToJSON(json: any): ContractCreate {
    return ContractCreateToJSONTyped(json, false);
}

export function ContractCreateToJSONTyped(value?: ContractCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract_number': value['contractNumber'],
        'contract_date': ((value['contractDate']).toISOString().substring(0,10)),
        'valid_date': value['validDate'] == null ? undefined : ((value['validDate'] as any).toISOString().substring(0,10)),
        'place_of_signing': value['placeOfSigning'],
        'currency': value['currency'],
        'exchange_rate': ExchangeRateToJSON(value['exchangeRate']),
        'supplier_name': value['supplierName'],
        'supplier_representative': value['supplierRepresentative'],
        'supplier_address': value['supplierAddress'],
        'supplier_bank': value['supplierBank'],
        'supplier_account': value['supplierAccount'],
        'buyer_name': value['buyerName'],
        'buyer_address': value['buyerAddress'],
        'buyer_bank': value['buyerBank'],
        'buyer_account': value['buyerAccount'],
        'goods_name': value['goodsName'],
        'quantity': value['quantity'],
        'price_per_unit': PricePerUnitToJSON(value['pricePerUnit']),
        'total_price': TotalPriceToJSON(value['totalPrice']),
        'payment_date': ((value['paymentDate']).toISOString().substring(0,10)),
        'delivery_terms': value['deliveryTerms'],
        'claim_period': value['claimPeriod'],
        'response_period': value['responsePeriod'],
    };
}

