/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PricePerUnit
 */
export interface PricePerUnit {
}

/**
 * Check if a given object implements the PricePerUnit interface.
 */
export function instanceOfPricePerUnit(value: object): value is PricePerUnit {
    return true;
}

export function PricePerUnitFromJSON(json: any): PricePerUnit {
    return PricePerUnitFromJSONTyped(json, false);
}

export function PricePerUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricePerUnit {
    return json;
}

export function PricePerUnitToJSON(json: any): PricePerUnit {
    return PricePerUnitToJSONTyped(json, false);
}

export function PricePerUnitToJSONTyped(value?: PricePerUnit | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

