/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';
import type { TotalAmount } from './TotalAmount';
import {
    TotalAmountFromJSON,
    TotalAmountFromJSONTyped,
    TotalAmountToJSON,
    TotalAmountToJSONTyped,
} from './TotalAmount';

/**
 * 
 * @export
 * @interface SpecificationCreate
 */
export interface SpecificationCreate {
    /**
     * 
     * @type {string}
     * @memberof SpecificationCreate
     */
    specNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof SpecificationCreate
     */
    specDate: Date;
    /**
     * 
     * @type {string}
     * @memberof SpecificationCreate
     */
    goodsDescription: string;
    /**
     * 
     * @type {Price}
     * @memberof SpecificationCreate
     */
    price: Price;
    /**
     * 
     * @type {number}
     * @memberof SpecificationCreate
     */
    volume: number;
    /**
     * 
     * @type {TotalAmount}
     * @memberof SpecificationCreate
     */
    totalAmount: TotalAmount;
}

/**
 * Check if a given object implements the SpecificationCreate interface.
 */
export function instanceOfSpecificationCreate(value: object): value is SpecificationCreate {
    if (!('specNumber' in value) || value['specNumber'] === undefined) return false;
    if (!('specDate' in value) || value['specDate'] === undefined) return false;
    if (!('goodsDescription' in value) || value['goodsDescription'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    return true;
}

export function SpecificationCreateFromJSON(json: any): SpecificationCreate {
    return SpecificationCreateFromJSONTyped(json, false);
}

export function SpecificationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpecificationCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'specNumber': json['spec_number'],
        'specDate': (new Date(json['spec_date'])),
        'goodsDescription': json['goods_description'],
        'price': PriceFromJSON(json['price']),
        'volume': json['volume'],
        'totalAmount': TotalAmountFromJSON(json['total_amount']),
    };
}

export function SpecificationCreateToJSON(json: any): SpecificationCreate {
    return SpecificationCreateToJSONTyped(json, false);
}

export function SpecificationCreateToJSONTyped(value?: SpecificationCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spec_number': value['specNumber'],
        'spec_date': ((value['specDate']).toISOString().substring(0,10)),
        'goods_description': value['goodsDescription'],
        'price': PriceToJSON(value['price']),
        'volume': value['volume'],
        'total_amount': TotalAmountToJSON(value['totalAmount']),
    };
}

