/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotalAmount
 */
export interface TotalAmount {
}

/**
 * Check if a given object implements the TotalAmount interface.
 */
export function instanceOfTotalAmount(value: object): value is TotalAmount {
    return true;
}

export function TotalAmountFromJSON(json: any): TotalAmount {
    return TotalAmountFromJSONTyped(json, false);
}

export function TotalAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalAmount {
    return json;
}

export function TotalAmountToJSON(json: any): TotalAmount {
    return TotalAmountToJSONTyped(json, false);
}

export function TotalAmountToJSONTyped(value?: TotalAmount | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

