/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotalPrice
 */
export interface TotalPrice {
}

/**
 * Check if a given object implements the TotalPrice interface.
 */
export function instanceOfTotalPrice(value: object): value is TotalPrice {
    return true;
}

export function TotalPriceFromJSON(json: any): TotalPrice {
    return TotalPriceFromJSONTyped(json, false);
}

export function TotalPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalPrice {
    return json;
}

export function TotalPriceToJSON(json: any): TotalPrice {
    return TotalPriceToJSONTyped(json, false);
}

export function TotalPriceToJSONTyped(value?: TotalPrice | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

