version: '3.8'

services:
  backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:password@host.docker.internal:5432/contracts_db
      - DEBUG=True
    volumes:
      - .:/app
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
