/* tslint:disable */
/* eslint-disable */
/**
 * Самый Крутой Бэк
 * Бэкэнд для управления договорами, счетами, платежами и шаблонами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  InvoiceResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    InvoiceResponseFromJSON,
    InvoiceResponseToJSON,
} from '../models/index';

export interface GetInvoicesContractsContractIdInvoicesGetRequest {
    contractId: number;
}

/**
 * 
 */
export class InvoicesApi extends runtime.BaseAPI {

    /**
     * Получить список инвойсов для контракта.
     * Get Invoices
     */
    async getInvoicesContractsContractIdInvoicesGetRaw(requestParameters: GetInvoicesContractsContractIdInvoicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InvoiceResponse>>> {
        if (requestParameters['contractId'] == null) {
            throw new runtime.RequiredError(
                'contractId',
                'Required parameter "contractId" was null or undefined when calling getInvoicesContractsContractIdInvoicesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/contracts/{contract_id}/invoices/`.replace(`{${"contract_id"}}`, encodeURIComponent(String(requestParameters['contractId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InvoiceResponseFromJSON));
    }

    /**
     * Получить список инвойсов для контракта.
     * Get Invoices
     */
    async getInvoicesContractsContractIdInvoicesGet(requestParameters: GetInvoicesContractsContractIdInvoicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InvoiceResponse>> {
        const response = await this.getInvoicesContractsContractIdInvoicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
