"""Update template model

Revision ID: 68def0585ebd
Revises: 557a6fa0969b
Create Date: 2025-02-26 17:27:51.665312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68def0585ebd'
down_revision: Union[str, None] = '557a6fa0969b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_contract_id', table_name='invoices')
    op.drop_index('ix_invoices_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_addendums_addendum_number', table_name='addendums')
    op.drop_index('ix_addendums_contract_id', table_name='addendums')
    op.drop_index('ix_addendums_id', table_name='addendums')
    op.drop_index('ix_addendums_invoice_number', table_name='addendums')
    op.drop_table('addendums')
    op.drop_index('ix_appendices_id', table_name='appendices')
    op.drop_table('appendices')
    op.drop_index('ix_templates_id', table_name='templates')
    op.drop_index('ix_templates_name', table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_contracts_contract_number', table_name='contracts')
    op.drop_index('ix_contracts_id', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_specifications_contract_id', table_name='specifications')
    op.drop_index('ix_specifications_id', table_name='specifications')
    op.drop_index('ix_specifications_spec_number', table_name='specifications')
    op.drop_table('specifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('spec_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('goods_description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='specifications_contract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='specifications_pkey')
    )
    op.create_index('ix_specifications_spec_number', 'specifications', ['spec_number'], unique=False)
    op.create_index('ix_specifications_id', 'specifications', ['id'], unique=False)
    op.create_index('ix_specifications_contract_id', 'specifications', ['contract_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('contracts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('contract_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contract_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('place_of_signing', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('valid_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier_representative', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier_inn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('supplier_bik', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('supplier_ogrn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('supplier_bank', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier_swift', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('supplier_account', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('buyer_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('buyer_bank', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('buyer_swift', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('buyer_account', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('buyer_tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('goods_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('delivery_terms', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('incoterms', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('claim_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contracts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_contracts_id', 'contracts', ['id'], unique=False)
    op.create_index('ix_contracts_contract_number', 'contracts', ['contract_number'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='payments_invoice_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dynamic_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='templates_pkey')
    )
    op.create_index('ix_templates_name', 'templates', ['name'], unique=False)
    op.create_index('ix_templates_id', 'templates', ['id'], unique=False)
    op.create_table('appendices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appendix_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('appendix_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='appendices_contract_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='appendices_pkey')
    )
    op.create_index('ix_appendices_id', 'appendices', ['id'], unique=False)
    op.create_table('addendums',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('addendum_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('addendum_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoice_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='addendums_contract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='addendums_pkey')
    )
    op.create_index('ix_addendums_invoice_number', 'addendums', ['invoice_number'], unique=False)
    op.create_index('ix_addendums_id', 'addendums', ['id'], unique=False)
    op.create_index('ix_addendums_contract_id', 'addendums', ['contract_id'], unique=False)
    op.create_index('ix_addendums_addendum_number', 'addendums', ['addendum_number'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='invoices_contract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoices_pkey')
    )
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.create_index('ix_invoices_contract_id', 'invoices', ['contract_id'], unique=False)
    # ### end Alembic commands ###
